### PR TITLE
Add prereleases feature

### PR DESCRIPTION
**Pull request by boxcee**
Closes https://github.com/mathieudutour/github-tag-action/issues/25

### CODE REVIEW

**Comment by boxcee** [comment]
@tombrouwer care to take a look?

**Comment by Wndrr** [comment]
I think you should add ".idea" to the gitignore. 
Is it expected that you commented

**Comment by boxcee** [comment]
@Wndrr My understanding is to only comment them out during development phase. They should be in here, correct.

**Comment by mathieudutour** [comment]
can you clean up the branch and keep the node_modules git ignored?

**Comment by boxcee** [comment]
@mathieudutour Sure! Done.

**Comment by mathieudutour** [comment]
merged as part of #37

**Pull request closed without merging**
